info:
    name: "[GET] Settings (handleApiSettingsGet)"
    type: http
    seq: 8

http:
    method: GET
    url: "{{HOST_BASE_URL}}/api/settings"
    auth: inherit

settings:
    encodeUrl: true
    timeout: 0
    followRedirects: true
    maxRedirects: 5
