info:
  name: "[POST] Settings (handleApiSettingsPost)"
  type: http
  seq: 9

http:
  method: POST
  url: "{{HOST_BASE_URL}}/api/settings"
  body:
    type: json
    data: |-
      {
        "ledCount": 5
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
